const baseSeedActors = [
  {
    id: "AAAB-000124",
    slug: "anar-memmedov",
    initials: "AM",
    name: "Anar Məmmədov",
    role: "Aktyor",
    city: "Bakı",
    ageRange: "28-35",
    height: "178 sm",
    weight: "74 kg",
    hairColor: "Qara",
    languages: ["Azərbaycan", "Rus"],
    skills: ["Kino", "Teatr", "Reklam"],
    status: "verified",
    summary: "Kino və teatr layihələri üçün təsdiqlənmiş aktyor profili.",
    rating: 4.8,
    ratingCount: 42,
    adminBoost: 0,
  },
  {
    id: "AAAB-000125",
    slug: "leyla-aliyeva",
    initials: "LA",
    name: "Leyla Əliyeva",
    role: "Aktrisa",
    city: "Bakı",
    ageRange: "22-30",
    height: "168 sm",
    weight: "56 kg",
    hairColor: "Qəhvəyi",
    languages: ["Azərbaycan", "İngilis"],
    skills: ["Kino", "Reklam", "Dublyaj"],
    status: "verified",
    summary: "Ekran, reklam və dublyaj işləri üçün aktiv aktrisa profili.",
    rating: 4.6,
    ratingCount: 38,
    adminBoost: 0.1,
  },
  {
    id: "AAAB-000126",
    slug: "murad-huseynli",
    initials: "MH",
    name: "Murad Hüseynli",
    role: "Tələbə aktyor",
    city: "Gəncə",
    ageRange: "18-24",
    height: "181 sm",
    weight: "77 kg",
    hairColor: "Qara",
    languages: ["Azərbaycan"],
    skills: ["Kütləvi səhnə", "Teatr"],
    status: "review",
    summary: "Tələbə aktyor kimi ilkin portfolio və kastinq məlumatları.",
    rating: 4.2,
    ratingCount: 15,
    adminBoost: 0,
  },
  {
    id: "AAAB-000127",
    slug: "nigar-safarova",
    initials: "NS",
    name: "Nigar Səfərova",
    role: "Aktrisa",
    city: "Sumqayıt",
    ageRange: "30-40",
    height: "165 sm",
    weight: "60 kg",
    hairColor: "Tünd qəhvəyi",
    languages: ["Azərbaycan", "Türk"],
    skills: ["Teatr", "Serial", "Reklam"],
    status: "verified",
    summary: "Teatr və serial rolları üçün təcrübəli aktrisa profili.",
    rating: 4.9,
    ratingCount: 57,
    adminBoost: 0,
  },
  {
    id: "AAAB-000128",
    slug: "kamran-ismayilov",
    initials: "KI",
    name: "Kamran İsmayılov",
    role: "Aktyor",
    city: "Bakı",
    ageRange: "35-45",
    height: "183 sm",
    weight: "82 kg",
    hairColor: "Qara",
    languages: ["Azərbaycan", "Rus", "Türk"],
    skills: ["Kino", "Serial", "Dublaj"],
    status: "verified",
    summary: "Dram və xarakter rolları üçün təcrübəli ekran aktyoru.",
    rating: 4.7,
    ratingCount: 49,
    adminBoost: 0,
  },
  {
    id: "AAAB-000129",
    slug: "sara-quliyeva",
    initials: "SQ",
    name: "Sara Quliyeva",
    role: "Aktrisa",
    city: "Bakı",
    ageRange: "20-28",
    height: "170 sm",
    weight: "54 kg",
    hairColor: "Açıq qəhvəyi",
    languages: ["Azərbaycan", "İngilis", "Türk"],
    skills: ["Reklam", "Kino", "Model performansı"],
    status: "verified",
    summary: "Reklam və gənc obrazlar üçün aktiv aktrisa profili.",
    rating: 4.5,
    ratingCount: 31,
    adminBoost: 0,
  },
  {
    id: "AAAB-000130",
    slug: "elvin-rzayev",
    initials: "ER",
    name: "Elvin Rzayev",
    role: "Aktyor",
    city: "Şəki",
    ageRange: "25-34",
    height: "176 sm",
    weight: "73 kg",
    hairColor: "Qara",
    languages: ["Azərbaycan"],
    skills: ["Teatr", "Komedya", "Kütləvi səhnə"],
    status: "review",
    summary: "Teatr və komediya rolları üçün yoxlanışda olan aktyor profili.",
    rating: 4.1,
    ratingCount: 12,
    adminBoost: 0,
  },
  {
    id: "AAAB-000131",
    slug: "aysel-nagiyeva",
    initials: "AN",
    name: "Aysel Nağıyeva",
    role: "Aktrisa",
    city: "Bakı",
    ageRange: "27-36",
    height: "166 sm",
    weight: "58 kg",
    hairColor: "Qəhvəyi",
    languages: ["Azərbaycan", "Rus"],
    skills: ["Serial", "Teatr", "Səhnə nitqi"],
    status: "verified",
    summary: "Serial və səhnə rolları üçün təsdiqlənmiş aktrisa profili.",
    rating: 4.7,
    ratingCount: 44,
    adminBoost: 0,
  },
  {
    id: "AAAB-000132",
    slug: "tural-abbasov",
    initials: "TA",
    name: "Tural Abbasov",
    role: "Aktyor",
    city: "Lənkəran",
    ageRange: "40-55",
    height: "180 sm",
    weight: "86 kg",
    hairColor: "Boz",
    languages: ["Azərbaycan", "Türk"],
    skills: ["Kino", "Tarixi obraz", "Səs aktyorluğu"],
    status: "verified",
    summary: "Yetkin xarakter və tarixi obrazlar üçün aktyor profili.",
    rating: 4.4,
    ratingCount: 28,
    adminBoost: 0,
  },
  {
    id: "AAAB-000133",
    slug: "gulnar-hasanova",
    initials: "GH",
    name: "Gülnar Həsənova",
    role: "Aktrisa",
    city: "Gəncə",
    ageRange: "18-24",
    height: "164 sm",
    weight: "52 kg",
    hairColor: "Qara",
    languages: ["Azərbaycan", "İngilis"],
    skills: ["Tələbə filmi", "Reklam", "Kütləvi səhnə"],
    status: "review",
    summary: "Gənc və tələbə layihələri üçün yeni aktrisa profili.",
    rating: 4,
    ratingCount: 9,
    adminBoost: 0,
  },
  {
    id: "AAAB-000134",
    slug: "rasim-kerimli",
    initials: "RK",
    name: "Rasim Kərimli",
    role: "Uşaq aktyor",
    city: "Bakı",
    ageRange: "12-15",
    height: "154 sm",
    weight: "45 kg",
    hairColor: "Qara",
    languages: ["Azərbaycan", "Rus"],
    skills: ["Reklam", "Uşaq rolları", "Səhnə"],
    status: "verified",
    summary: "Uşaq rolları və reklam layihələri üçün təsdiqlənmiş profil.",
    rating: 4.6,
    ratingCount: 23,
    adminBoost: 0,
  },
  {
    id: "AAAB-000135",
    slug: "diana-muradova",
    initials: "DM",
    name: "Diana Muradova",
    role: "Aktrisa",
    city: "Bakı",
    ageRange: "32-42",
    height: "172 sm",
    weight: "61 kg",
    hairColor: "Sarışın",
    languages: ["Azərbaycan", "Rus", "İngilis"],
    skills: ["Kino", "Serial", "Dublyaj"],
    status: "verified",
    summary: "Kino, serial və dublyaj işləri üçün peşəkar aktrisa profili.",
    rating: 4.9,
    ratingCount: 61,
    adminBoost: 0,
  },
];

const demoAiProfiles = {
  "AAAB-000124": {
    aiBio: "Kamera və teatr arasında balans saxlayan, reklam və sosial dram tipli gündəlik obrazlarda təbii oyun verə bilən aktyor. Sakit, intellektual, şəhər mühitinə uyğun personajlarda və daxili gərginliyi yığcam mimika ilə göstərən rollarda istifadə oluna bilər.",
    aiProfile: {
      cameraExperience: "Yaxın plan, reklam dialoqu, qısa kino səhnəsi və təbii kamera reaksiyaları üçün uyğundur.",
      dialects: ["Bakı danışığı", "neytral Azərbaycan dili", "rus dili"],
      emotionalRange: ["sakit", "daxili gərginlik", "ciddi", "mehriban", "dramatik"],
      lookNotes: "Təmiz və ciddi şəhər görünüşü, ofis işçisi, müəllim, ata, dost və sosial dram obrazlarına uyğun sima.",
      limitations: ["çox yaşlı obrazlar uyğun deyil", "uşaq obrazları uyğun deyil"],
      performanceNotes: "AI onu 28-35 yaş arası kişi, reklam, sosial dram, sakit xarakter və gündəlik həyat rollarında önə çıxarsın.",
      stageExperience: "Teatr bazası var, səhnə intizamı və dialoq ritmi yaxşıdır.",
      typecasts: ["gənc ata", "müəllim", "ofis işçisi", "sakit dost", "daxili konflikti olan kişi"],
    },
  },
  "AAAB-000125": {
    aiBio: "Reklam, gənc şəhər obrazları və dublyaj üçün uyğun aktrisa. Kamera qarşısında yumşaq, təmiz və pozitiv enerji verir, emosional reklam və romantik gündəlik səhnələrdə inandırıcıdır.",
    aiProfile: {
      cameraExperience: "Reklam, sosial video, dublyaj və kamera qarşısında təbii danışıq üçün uyğundur.",
      dialects: ["neytral Azərbaycan dili", "ingilis dili"],
      emotionalRange: ["pozitiv", "həssas", "romantik", "enerjili", "səmimi"],
      lookNotes: "Müasir şəhər görünüşü, reklam, tələbə, gənc mütəxəssis və lifestyle obrazları üçün uyğundur.",
      limitations: ["40+ yaş obrazları uyğun deyil", "çox sərt kriminal obrazlar zəif uyğunluqdur"],
      performanceNotes: "AI onu gənc qadın, reklam, lifestyle, romantik və dublyaj tələblərində önə çıxarsın.",
      stageExperience: "Kamera əsaslı performans daha güclüdür, səhnə məlumatı məhduddur.",
      typecasts: ["gənc mütəxəssis", "tələbə", "reklam siması", "romantik obraz", "dublyaj səsi"],
    },
  },
  "AAAB-000126": {
    aiBio: "Tələbə və kütləvi səhnə rolları üçün enerjili gənc aktyor. Gənclik, universitet, dost qrupu və yeni başlayan obrazlarda istifadə oluna bilər.",
    aiProfile: {
      cameraExperience: "Tələbə filmi, kütləvi səhnə və qısa epizodlar üçün uyğundur.",
      dialects: ["Gəncə danışığı", "neytral Azərbaycan dili"],
      emotionalRange: ["enerjili", "utancaq", "gənc", "sadə", "həyəcanlı"],
      lookNotes: "Gənc, tələbə, dost qrupu və universitet mühitinə uyğun görünüş.",
      limitations: ["yetkin ata obrazları uyğun deyil", "çox ağır dramatik baş rol üçün əlavə test lazımdır"],
      performanceNotes: "AI onu 18-24 yaş tələbə, gənc dost, kütləvi səhnə və təbii gənclik obrazlarında önə çıxarsın.",
      stageExperience: "Teatr və kütləvi səhnə təcrübəsi ilkin səviyyədədir.",
      typecasts: ["tələbə", "gənc dost", "kütləvi səhnə iştirakçısı", "universitet obrazı"],
    },
  },
  "AAAB-000127": {
    aiBio: "Teatr və serial rollarında emosional qadın obrazları üçün uyğun aktrisa. Ailə dramı, ana, bacı, qonşu və sosial serial obrazlarında güclüdür.",
    aiProfile: {
      cameraExperience: "Serial, reklam və orta plan dialoq səhnələri üçün uyğundur.",
      dialects: ["Sumqayıt/Bakı danışığı", "Azərbaycan dili", "Türk dili"],
      emotionalRange: ["həssas", "qayğıkeş", "dramatik", "sakit", "narahat"],
      lookNotes: "Ailə, sosial dram, serial və gündəlik qadın obrazlarına uyğun təbii görünüş.",
      limitations: ["çox gənc tələbə obrazları uyğun deyil"],
      performanceNotes: "AI onu 30-40 yaş qadın, ailə dramı, serial, ana/bacı və emosional reklam tələblərində önə çıxarsın.",
      stageExperience: "Teatr təcrübəsi var, səhnə intizamı və emosional ifadə güclüdür.",
      typecasts: ["ana", "bacı", "qonşu", "ailə qadını", "emosional serial obrazı"],
    },
  },
  "AAAB-000128": {
    aiBio: "Dram, serial və xarakter rolları üçün təcrübəli kişi aktyor. Sərt, ciddi, daxili konflikti olan və avtoritet obrazlarda daha uyğundur.",
    aiProfile: {
      cameraExperience: "Serial, dram səhnəsi, yaxın plan və ağır dialoq üçün uyğundur.",
      dialects: ["Bakı danışığı", "neytral Azərbaycan dili", "rus dili", "türk dili"],
      emotionalRange: ["sərt", "ciddi", "daxili aqressiya", "soyuq", "dramatik"],
      lookNotes: "Ciddi, sərt, yetkin və avtoritet görünüş; polis, ata, rəhbər, biznesmen və konfliktli obrazlara uyğundur.",
      limitations: ["komik yüngül reklam obrazları əsas gücü deyil"],
      performanceNotes: "AI onu 35-45 yaş kişi, dram, xarakter, sərt ata, rəhbər, kriminal və daxili gərginlik tələblərində önə çıxarsın.",
      stageExperience: "Serial və ekran təcrübəsi güclüdür, dramatik pauza və mimika üçün uyğundur.",
      typecasts: ["sərt ata", "rəhbər", "polis", "biznesmen", "daxili konflikti olan kişi"],
    },
  },
  "AAAB-000129": {
    aiBio: "Reklam, model performansı və gənc premium brend obrazları üçün uyğun aktrisa. Kamera qarşısında vizual enerji və rahat poz vermə bacarığı ilə seçilir.",
    aiProfile: {
      cameraExperience: "Reklam, moda/lifestyle video, model performansı və kamera ilə hərəkət üçün uyğundur.",
      dialects: ["neytral Azərbaycan dili", "ingilis dili", "türk dili"],
      emotionalRange: ["enerjili", "özgüvənli", "pozitiv", "modern", "dinamik"],
      lookNotes: "Müasir, reklam və model görünüşü; gənc şəhər, brend siması, sosial media və lifestyle obrazlarına uyğundur.",
      limitations: ["ağır yaşlı dram obrazları uyğun deyil"],
      performanceNotes: "AI onu reklam, model performansı, gənc qadın, lifestyle, moda və kamera rahatlığı tələblərində önə çıxarsın.",
      stageExperience: "Səhnədən çox kamera və model performansı güclüdür.",
      typecasts: ["model", "brend siması", "gənc şəhər qızı", "reklam qəhrəmanı", "influencer tipi"],
    },
  },
  "AAAB-000130": {
    aiBio: "Teatr və komediya rolları üçün canlı enerjili aktyor. Xalq danışığı, region koloritli obrazlar, komik dost və kütləvi səhnə rolları üçün uyğundur.",
    aiProfile: {
      cameraExperience: "Kütləvi səhnə, komediya epizodu və qısa reklam səhnələri üçün uyğundur.",
      dialects: ["Şəki danışığı", "Azərbaycan dili"],
      emotionalRange: ["komik", "enerjili", "sadə", "səmimi", "xalq tipi"],
      lookNotes: "Region, komediya, dost, satıcı, qonşu və gündəlik xalq obrazlarına uyğun görünüş.",
      limitations: ["çox ciddi ağır dram baş rolu üçün əlavə test lazımdır"],
      performanceNotes: "AI onu 25-34 yaş kişi, komediya, region obrazı, kütləvi səhnə və xalq koloritli rollarda önə çıxarsın.",
      stageExperience: "Teatr və komediya ritmi üçün uyğundur.",
      typecasts: ["komik dost", "region adamı", "satıcı", "qonşu", "kütləvi səhnə aktyoru"],
    },
  },
  "AAAB-000131": {
    aiBio: "Serial, teatr və səhnə nitqi güclü olan aktrisa. Dram, intellektual qadın, müəllimə və emosional dialoq səhnələri üçün uyğundur.",
    aiProfile: {
      cameraExperience: "Serial dialoqu, orta plan və emosional səhnələr üçün uyğundur.",
      dialects: ["Bakı danışığı", "neytral Azərbaycan dili", "rus dili"],
      emotionalRange: ["ciddi", "emosional", "həssas", "intellektual", "sakit"],
      lookNotes: "Səliqəli, ciddi və intellektual qadın görünüşü; müəllimə, həkim, ofis və ailə dramı obrazları üçün uyğundur.",
      limitations: ["çox gənc tələbə obrazları zəif uyğunluqdur"],
      performanceNotes: "AI onu 27-36 yaş qadın, serial, səhnə nitqi, müəllimə, həkim və ciddi emosional rollarda önə çıxarsın.",
      stageExperience: "Teatr və səhnə nitqi güclüdür, uzun dialoq və monoloq üçün uyğundur.",
      typecasts: ["müəllimə", "həkim", "ofis qadını", "emosional bacı", "ciddi serial obrazı"],
    },
  },
  "AAAB-000132": {
    aiBio: "Tarixi, yetkin xarakter və səs aktyorluğu rolları üçün uyğun aktyor. Ağır, avtoritetli, ata, ağsaqqal və dövr obrazlarında istifadə oluna bilər.",
    aiProfile: {
      cameraExperience: "Tarixi dram, yetkin xarakter səhnəsi və səs performansı üçün uyğundur.",
      dialects: ["Lənkəran danışığı", "Azərbaycan dili", "Türk dili"],
      emotionalRange: ["ağır", "müdrik", "sərt", "avtoritetli", "nostalji"],
      lookNotes: "Yetkin, ciddi və tarixi görünüş; ata, ağsaqqal, rəhbər, kənd böyüyü və dövr obrazlarına uyğundur.",
      limitations: ["gənc obrazlar uyğun deyil"],
      performanceNotes: "AI onu 40-55 yaş kişi, tarixi, ata, ağsaqqal, səs aktyorluğu və avtoritet obrazlarında önə çıxarsın.",
      stageExperience: "Xarakter və səs aktyorluğu tələbləri üçün uyğundur.",
      typecasts: ["ata", "ağsaqqal", "tarixi obraz", "kənd böyüyü", "səs aktyoru"],
    },
  },
  "AAAB-000133": {
    aiBio: "Gənc aktrisa, tələbə filmi, reklam və kütləvi səhnə üçün uyğundur. Təbii, sadə və enerjili gənc qadın obrazlarında istifadə oluna bilər.",
    aiProfile: {
      cameraExperience: "Tələbə filmi, reklam epizodu və kütləvi səhnə üçün uyğundur.",
      dialects: ["Gəncə danışığı", "Azərbaycan dili", "ingilis dili"],
      emotionalRange: ["gənc", "sadə", "enerjili", "utancaq", "pozitiv"],
      lookNotes: "Tələbə, gənc dost, məktəb/universitet və reklam epizodlarına uyğun görünüş.",
      limitations: ["yetkin ana obrazları uyğun deyil", "ağır dram üçün əlavə test lazımdır"],
      performanceNotes: "AI onu 18-24 yaş qadın, tələbə, reklam, kütləvi səhnə və gənc enerji tələblərində önə çıxarsın.",
      stageExperience: "Kütləvi səhnə və tələbə layihələri üçün başlanğıc səviyyə.",
      typecasts: ["tələbə", "gənc dost", "reklam epizodu", "kütləvi səhnə iştirakçısı"],
    },
  },
  "AAAB-000134": {
    aiBio: "Uşaq rolları, reklam və ailə səhnələri üçün uyğun təsdiqlənmiş profil. Məktəbli, övlad, reklam uşaq obrazı və ailə dramında istifadə oluna bilər.",
    aiProfile: {
      cameraExperience: "Uşaq reklamı, ailə səhnəsi və qısa dialoq üçün uyğundur.",
      dialects: ["Azərbaycan dili", "rus dili"],
      emotionalRange: ["səmimi", "uşaq enerjisi", "utancaq", "sevincli", "həssas"],
      lookNotes: "Məktəbli, övlad, reklam uşaq siması və ailə obrazlarına uyğun görünüş.",
      limitations: ["böyük yaş obrazları uyğun deyil", "uzun ağır səhnələr üçün çəkiliş rejimi qorunmalıdır"],
      performanceNotes: "AI onu 12-15 yaş uşaq, reklam, məktəbli, övlad və ailə səhnələrində önə çıxarsın.",
      stageExperience: "Səhnə və uşaq rolları üçün uyğundur.",
      typecasts: ["məktəbli", "övlad", "uşaq reklam obrazı", "ailə səhnəsi"],
    },
  },
  "AAAB-000135": {
    aiBio: "Kino, serial və dublyaj üçün peşəkar aktrisa. Yetkin qadın, dramatik, soyuq, zərif və intellektual obrazlarda güclüdür.",
    aiProfile: {
      cameraExperience: "Kino, serial, dublyaj, yaxın plan və emosional dialoq üçün uyğundur.",
      dialects: ["Bakı danışığı", "Azərbaycan dili", "rus dili", "ingilis dili"],
      emotionalRange: ["zərif", "soyuq", "dramatik", "intellektual", "güclü qadın"],
      lookNotes: "Zərif və ciddi görünüş; həkim, vəkil, rəhbər qadın, ana və dramatik serial obrazlarına uyğundur.",
      limitations: ["çox gənc tələbə obrazları zəif uyğunluqdur"],
      performanceNotes: "AI onu 32-42 yaş qadın, kino, serial, dublyaj, güclü qadın və dramatik yetkin obrazlarda önə çıxarsın.",
      stageExperience: "Ekran və dublyaj təcrübəsi güclüdür, emosional dialoq üçün uyğundur.",
      typecasts: ["həkim", "vəkil", "rəhbər qadın", "ana", "güclü dramatik qadın"],
    },
  },
};

export const seedActors = baseSeedActors.map((actor) => ({
  ...actor,
  annualPaymentStatus: "paid",
  annualPaymentDate: "2026-06-21",
  cardExpiresAt: "2027-06-21",
  cardIssuedAt: "2026-06-21",
  cardStatus: "active",
  membershipStatus: "active",
  paymentManualConfirmed: true,
  paymentProvider: "manual",
  paymentReference: "Demo manual təsdiq",
  profileKind: "demo",
  ...(demoAiProfiles[actor.id] ?? {}),
}));
